// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aedgvmlresoxbbmksjju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlZGd2bWxyZXNveGJibWtzamp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjMwNDcsImV4cCI6MjA1NzAzOTA0N30.ciOil0s2FA3KMS34BONYFnynbLzQj1ovC-6Oh2xpWvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);